server:
  port: 8080

logging:
  level:
    root: info
referer:
  refererDomain:
    - https://www.baidu.com
    - https://yanruyu.site
path:
  file: file:C:/photoproject
spring:
  freemarker:
    charset: UTF-8
    suffix: .html
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
    request-context-attribute: request
  profiles:
    active: dev




