mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    #----------单点登录服务----------#
    #单点登录服务端地址
sso:
  server:
    url: http://localhost:8082
    #客户端应用密钥信息
  app:
    id: 123
    secret: 123456
    #----------单点登录服务----------#


file:
  path:
    section: C:/upload/temp
    finish: C:/upload/finish

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso_photo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  profiles: dev
  redis:
    host: 121.40.169.157
    port: 6379
#    password:
