server:
  port: 8080

logging:
  level:
    root: info

spring:
  freemarker:
    charset: UTF-8
    suffix: .html
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
    request-context-attribute: request
  profiles:
    active: dev




