---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xhx.
--- DateTime: 2022/3/5 15:45
--- Description: 热度排行榜增加热度逻辑
local redisRankKey = KEYS[1];
local photoName = KEYS[2];
local size = redis.call("ZCARD", redisRankKey);
if size >= 51 then
    local min = redis.call("ZRANGE", 0, 0);
    if min ~= nil then
        redis.call("ZREM", min);
    end
end
redis.call("ZINCRBY", redisRankKey, 10, photoName);


